### ISSUE TITLE
How to use third part vendor libraries

### ISSUE THREAD

**Issue by pank789** [vue-microfrontends/navbar#1]
Hi,

I would like to use the third party control from vuetify and kendo.

But when the output is generated it doesnt create chunks and says unable to find the kendo.

how should we go ahead for the vendor library support in child apps.

app-errors.js:11 Uncaught ReferenceError: application 'app1' died in status LOADING_SOURCE_CODE: kendo is not defined

It will good if you can add the vue store in child app.

**Comment by internettrans** [comment]
[Relevant documentation](https://single-spa.js.org/docs/recommended-setup#in-browser-versus-build-time-modules)

You can add third party vendor libraries in two different ways:

1. As a build-time module (from node_modules)
2. As a runtime module (from import map inside of browser)

For build-time module, simply `yarn add kendo vuetify`.

For runtime module, add kendo and/or vuetify to [this file in shared-dependencies](https://github.com/vue-microfrontends/shared-dependencies/blob/master/importmap.json). The file should point to a UMD or System.register bundle for those dependencies ([example](https://unpkg.com/vuetify@2.2.15/dist/vuetify.js)). Then inside of [vue.config.js](https://github.com/vue-microfrontends/navbar/blob/55db8b452459f369ab32400ddcf02de67365ed38/vue.config.js#L12), add kendo and/or vuetify as webpack externals.

**Comment by pank789** [comment]
Hi,

I have added currently as per point 1 but when the child app is loaded, i am getting error which i have shared earlier.
Plz note here kendo is added in child app

**Comment by internettrans** [comment]
This sounds like you have not installed `kendo` properly, or that you are importing it incorrectly. Can you show it in your package.json and also the code that imports it?

**Comment by pank789** [comment]
_Package.json under dependencies, i have_

"dependencies": {
"@progress/kendo-ui": "2018.2.822",
"@progress/kendo-theme-default": "2.55.0",
"@progress/kendo-base-components-vue-wrapper": "2018.2.620",
"@progress/kendo-dropdowns-vue-wrapper": "2018.2.620",
.....
......
}

_and in my main.js file so that is is availabe accross entire  application_

import { AutoComplete, ComboBox, DropDownList, MultiSelect, DropdownsInstaller } from '@progress/kendo-dropdowns-vue-wrapper';

Vue.use(DropdownsInstaller);

and complied normally in production mode. so, it generated the index.html and js/app.js file along with few other normal files which would get generated with vue build.

As per my understanding since, we are using system js webpack interop, the output is targeted to library of target type as "system" which i believe is "amd" internaly and hence all the external modules should get packed under app.js along with css.

But this seems to be not working for me.

**Comment by internettrans** [comment]
> As per my understanding since, we are using system js webpack interop, the output is targeted to library of target type as "system" which i believe is "amd" internaly.

System.register format is not AMD internally. You can read more about System.register [in these systemjs docs](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md).

> hence all the external modules should get packed under app.js along with css.

This is not required. You can still use external CSS if you'd like to. To do so, you'll need to 1) configure the public path via `System.resolve()` (as shown [here](https://github.com/vue-microfrontends/navbar/blob/master/src/set-public-path.js)), and 2) use `__webpack_public_path__` in your calculation of the href for the link element. Example:

```js
const link = Object.assign(document.createElement("link"), {
  rel: "stylesheet",
  href: __webpack_public_path__ + "filename.css"
});
document.head.appendChild(link);
```

Honestly, I'm a bit confused about what you're trying to accomplish. Are you trying to use the kendo library, or are you trying to load external CSS? Is kendo a webpack external or not?

Your import map shouldn't matter at all if kendo is not a webpack external. See [this explanation](https://single-spa.js.org/docs/recommended-setup#in-browser-versus-build-time-modules) of the difference between build-time and in-browser modules. I would suggest keeping kendo as a build-time module to start, which means that you do not need to do anything with your import map

**Comment by pank789** [comment]
Hi,
I want to use kendo library as build time module and when deployed in iis as part of child app it should get loaded.

As per ur suggestion i have configured in package.json and imported properly in main.js but when using the root-mf module in deployed mode in iis, child module doesnt get loaded, it fails with kendo undefined error.

I will redo the entire thing again with fresh set of code a.nd will let you know again.

Thanks

**Comment by internettrans** [comment]
I won't be able to help you debug this further without a code example. However, this sounds like an error unrelated to single-spa. It's just package.json + webpack

**Comment by pank789** [comment]
@joeldenning  thank you for ur inputs ,

I tried the changes first in rate- dogs and found it working fine.
Post that on debugging my existing project figured out our mistake that we were making in porject.

Since it was exisiting project we were assigning window.vue = vue which was nit able to recognize kendo.

Post commenting this everything started working.

Thanks
