### ISSUE TITLE
unable to overrides import map in localhost during development

### ISSUE THREAD

**Issue by calvin17** [vue-microfrontends/navbar#3]
1. Cloned the navbar in local from git
2. run navbar in localhost ( yarn serve ) - App running at  https://localhost:8501/
3. overrides the @vue-mf/navbar in https://vue.microfrontends.app/ unable to view the local changes
4. after Apply override dev tool shows Inline Override.
Changes in local are not reflecting on the website.

![added_to_override_import_maps_window](https://user-images.githubusercontent.com/16399452/81147835-c3bd8580-8f98-11ea-8f43-31e3c6fde032.png)
![nav_localhost](https://user-images.githubusercontent.com/16399452/81147837-c4561c00-8f98-11ea-8dce-66ca14a84a32.png)
![not_overriding_with_localhost](https://user-images.githubusercontent.com/16399452/81147839-c4eeb280-8f98-11ea-9bae-2bbfece778a8.png)

**Comment by calvin17** [comment]
> 1. Cloned the navbar in local from git
> 2. run navbar in localhost ( yarn serve ) - App running at  https://localhost:8501/
> 3. overrides the @vue-mf/navbar in https://vue.microfrontends.app/ unable to view the local changes
> 4. after Apply override dev tool shows Inline Override.
>    Changes in local are not reflecting on the website.
> 
> ![added_to_override_import_maps_window](https://user-images.githubusercontent.com/16399452/81147835-c3bd8580-8f98-11ea-8f43-31e3c6fde032.png)
> ![nav_localhost](https://user-images.githubusercontent.com/16399452/81147837-c4561c00-8f98-11ea-8dce-66ca14a84a32.png)
> ![not_overriding_with_localhost](https://user-images.githubusercontent.com/16399452/81147839-c4eeb280-8f98-11ea-9bae-2bbfece778a8.png)

working good if we pass as //localhost:8501/js/app.js instead of https://localhost:8501/js/app.js

**Comment by internettrans** [comment]
Ah thanks for bringing this to my attention - I have updated the readme in https://github.com/vue-microfrontends/navbar/commit/e7434d2a863655a1bfa9ef83826fcc499ee87908 to remove the `https:` prefix so that others will not run into this. I plan on making the same change in all the other repos as well

**Comment by internettrans** [comment]
After thinking about this further, I actually reversed that commit in https://github.com/vue-microfrontends/navbar/commit/6addb90e0c5d6301ff9a949bd04664f51806aebe. The vue.config.js forces https when you run `serve`, so I think in this example it should always be on HTTPS.

Did you see something different? Why didn't https work for you?

**Comment by calvin17** [comment]
currently https:// also working for me, after restarting the browser. Thank you.
